// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC77adnY4NoJN7vm-7PvixiuoOYuSfHxCc',
    appId: '1:45849567244:web:beea22eb5554044d7ace29',
    messagingSenderId: '45849567244',
    projectId: 'fir-c4b66',
    authDomain: 'fir-c4b66.firebaseapp.com',
    storageBucket: 'fir-c4b66.firebasestorage.app',
    measurementId: 'G-33RE3JN9K9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB33x0zjo4vxKumBUcyLnYx8jItLC1hTgo',
    appId: '1:45849567244:android:816be8f95f696f9c7ace29',
    messagingSenderId: '45849567244',
    projectId: 'fir-c4b66',
    storageBucket: 'fir-c4b66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDww8CiDXvm4MJWGYpLxpn4quaVdYB8t6U',
    appId: '1:45849567244:ios:28480564412c4e3d7ace29',
    messagingSenderId: '45849567244',
    projectId: 'fir-c4b66',
    storageBucket: 'fir-c4b66.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDww8CiDXvm4MJWGYpLxpn4quaVdYB8t6U',
    appId: '1:45849567244:ios:28480564412c4e3d7ace29',
    messagingSenderId: '45849567244',
    projectId: 'fir-c4b66',
    storageBucket: 'fir-c4b66.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC77adnY4NoJN7vm-7PvixiuoOYuSfHxCc',
    appId: '1:45849567244:web:90d063367606d67d7ace29',
    messagingSenderId: '45849567244',
    projectId: 'fir-c4b66',
    authDomain: 'fir-c4b66.firebaseapp.com',
    storageBucket: 'fir-c4b66.firebasestorage.app',
    measurementId: 'G-64CCDX9MB2',
  );
}
